"""Add reserved_by_id to Game

Revision ID: 12c1f14e8096
Revises: c216c673da98
Create Date: 2025-04-20 15:49:44.936713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c1f14e8096'
down_revision: Union[str, None] = 'c216c673da98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('reserved_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['reserved_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'reserved_by_id')
    # ### end Alembic commands ###
