"""Add reserved_by_id to Game

Revision ID: 9edda18676ed
Revises: 12c1f14e8096
Create Date: 2025-04-20 15:51:12.208091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9edda18676ed'
down_revision: Union[str, None] = '12c1f14e8096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
