"""initial

Revision ID: f55628b0f37b
Revises: 53f0d23c94cb
Create Date: 2025-02-24 00:45:29.187232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55628b0f37b'
down_revision: Union[str, None] = '53f0d23c94cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores')
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',

    )
    op.create_table('stores',

    )
    # ### end Alembic commands ###
